package application.views.technologyFolders;

public interface TechnologyFoldersConstants {

    String TEXTFIELD_NAME = "TEXTFIELD_NAME";

    String COMBOBOX_LEDGER = "COMBOBOX_LEDGER";
    String COMBOBOX_AVAILABLE_CONDITION_HAS_DLC = "COMBOBOX_AVAILABLE_CONDITION_HAS_DLC";
    String COMBOBOX_CONDITION_NOT_HAS_DLC = "COMBOBOX_CONDITION_NOT_HAS_DLC";

    String CHECKBOX_DOCTRINE = "CHECKBOX_DOCTRINE";
    String CHECKBOX_AVAILABLE_CONDITION = "CHECKBOX_AVAILABLE_CONDITION";
    String CHECKBOX_NOT_CONDITION = "CHECKBOX_NOT_CONDITION";

    String LABEL_AVAILABLE_CONDITION_HAS_DLC = "LABEL_AVAILABLE_CONDITION_HAS_DLC";
    String LABEL_NOT_CONDITION = "LABEL_NOT_CONDITION";
    String LABEL_NOT_CONDITION_HAS_DLC = "LABEL_NOT_CONDITION_HAS_DLC";
    String LABEL_NAME = "LABEL_NAME";
    String LABEL_LEDGER = "LABEL_LEDGER";
    String LABEL_DOCTRINE = "LABEL_DOCTRINE";
    String LABEL_AVAILABLE_CONDITION = "LABEL_AVAILABLE_CONDITION";

    String BUTTON_ADD = "BUTTON_ADD";
    String BUTTON_REMOVE = "BUTTON_REMOVE";
    String BUTTON_CLEAR = "BUTTON_CLEAR";

    String SCROLLING_LIST_FOLDERS = "SCROLLING_LIST_FOLDERS_MAIN";

}
